#!/usr/bin/env bash
# Build a MyShop mobile app for production.
#
#   tool/build.sh client android         # AAB at apps/client/build/app/outputs/bundle/release/
#   tool/build.sh client ios             # archive that opens in Xcode for App Store upload
#   tool/build.sh provider android
#   tool/build.sh provider ios
#
# Reads `.env.prod` (gitignored — copy from `.env.dev.example` and fill in
# the PRODUCTION-restricted keys) and threads the values through every
# build surface that needs them:
#
#   - Dart code: `--dart-define=KEY=value` for every line in `.env.prod`.
#   - Android native: writes `apps/<app>/android/local.properties`'s
#     `MAPS_API_KEY` so AndroidManifest's `${MAPS_API_KEY}` placeholder
#     resolves at native build time.
#   - iOS native: writes `apps/<app>/ios/Flutter/Secrets.xcconfig` so the
#     `Info.plist` `$(GOOGLE_MAPS_API_KEY)` substitution resolves. Both
#     Debug.xcconfig and Release.xcconfig `#include?` it.
#
# All three files are gitignored. The script is the only thing that touches
# them — never commit them, never paste keys into the Xcode UI.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

if [[ $# -lt 2 ]]; then
  echo "usage: tool/build.sh <client|provider> <android|ios> [extra flutter args...]" >&2
  exit 2
fi

APP="$1"
PLATFORM="$2"
shift 2

case "$APP" in
  client|provider) ;;
  *)
    echo "error: app must be 'client' or 'provider', got '$APP'" >&2
    exit 2
    ;;
esac

case "$PLATFORM" in
  android|ios) ;;
  *)
    echo "error: platform must be 'android' or 'ios', got '$PLATFORM'" >&2
    exit 2
    ;;
esac

ENV_FILE="$REPO_ROOT/.env.prod"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found. Copy .env.dev.example to .env.prod and fill in the PRODUCTION-restricted keys." >&2
  exit 1
fi

# Parse `.env.prod` once into a flat `--dart-define` array and pluck the
# few keys the native side needs into plain shell variables.
#
# Avoids `declare -A` (associative arrays) so the script works on macOS's
# stock bash 3.2 as well as the bash 5+ that ships on GitHub Actions runners.
DEFINES=()
GOOGLE_MAPS_API_KEY=""
while IFS='=' read -r key value; do
  key="${key#"${key%%[![:space:]]*}"}"
  [[ -z "$key" || "$key" == \#* ]] && continue
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  DEFINES+=("--dart-define=${key}=${value}")
  # Native-side passthroughs — additive `if` rather than associative
  # lookup so the script stays compatible with old bash. Add another
  # branch here if a new native-side env var is introduced.
  if [[ "$key" == "GOOGLE_MAPS_API_KEY" ]]; then
    GOOGLE_MAPS_API_KEY="$value"
  fi
done < "$ENV_FILE"

if [[ -z "$GOOGLE_MAPS_API_KEY" ]]; then
  echo "error: GOOGLE_MAPS_API_KEY missing from $ENV_FILE — required for production build." >&2
  exit 1
fi

APP_DIR="$REPO_ROOT/apps/$APP"

if [[ "$PLATFORM" == "android" ]]; then
  # `MAPS_API_KEY` in `android/local.properties` is what
  # `manifestPlaceholders` reads to fill `${MAPS_API_KEY}` in
  # AndroidManifest.xml at build time.
  LOCAL_PROPS="$APP_DIR/android/local.properties"
  if [[ -f "$LOCAL_PROPS" ]]; then
    # Strip any existing MAPS_API_KEY line so we don't end up with two.
    sed -i.bak '/^MAPS_API_KEY=/d' "$LOCAL_PROPS"
    rm -f "$LOCAL_PROPS.bak"
  fi
  echo "MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> "$LOCAL_PROPS"
  echo "→ wrote MAPS_API_KEY to $LOCAL_PROPS"
fi

if [[ "$PLATFORM" == "ios" ]]; then
  # The Info.plist `$(GOOGLE_MAPS_API_KEY)` substitution resolves via the
  # active xcconfig chain. We write a small Secrets.xcconfig — gitignored,
  # rewritten on every build — and Debug/Release.xcconfig `#include?` it.
  SECRETS_XCCONFIG="$APP_DIR/ios/Flutter/Secrets.xcconfig"
  cat > "$SECRETS_XCCONFIG" <<EOF
// Auto-generated by tool/build.sh from .env.prod — do NOT commit.
// Re-run tool/build.sh after rotating production keys.
GOOGLE_MAPS_API_KEY = $GOOGLE_MAPS_API_KEY
EOF
  echo "→ wrote $SECRETS_XCCONFIG"
fi

cd "$APP_DIR"

case "$PLATFORM" in
  android)
    echo "→ flutter build appbundle (release) for apps/$APP with ${#DEFINES[@]} dart-defines"
    exec flutter build appbundle --release "${DEFINES[@]}" "$@"
    ;;
  ios)
    echo "→ flutter build ipa (release) for apps/$APP with ${#DEFINES[@]} dart-defines"
    echo "  After this completes, open build/ios/archive/Runner.xcarchive in Xcode → Distribute App."
    exec flutter build ipa --release "${DEFINES[@]}" "$@"
    ;;
esac
