#!/usr/bin/env bash
# Run a MyShop mobile app with the local-dev keys baked in.
#
#   tool/run.sh client                # runs apps/client on the default device
#   tool/run.sh provider              # runs apps/provider on the default device
#   tool/run.sh client -d <deviceId>  # pass extra flutter-run flags after the app name
#
# Reads `.env.dev` (gitignored — copy from `.env.dev.example`) and passes
# every variable through to `flutter run` as a `--dart-define`. Mirrors what
# the v1.0 secret cleanup expects at runtime (`GOOGLE_MAPS_API_KEY`,
# `MAPBOX_ACCESS_TOKEN`, `MAPBOX_STYLE_URL`, etc).

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

if [[ $# -lt 1 ]]; then
  echo "usage: tool/run.sh <client|provider> [extra flutter args...]" >&2
  exit 2
fi

APP="$1"
shift

case "$APP" in
  client|provider) ;;
  *)
    echo "error: app must be 'client' or 'provider', got '$APP'" >&2
    exit 2
    ;;
esac

ENV_FILE="$REPO_ROOT/.env.dev"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found. Copy .env.dev.example and fill in the values." >&2
  exit 1
fi

# Source the env file in a way that tolerates blank lines and comments.
# Each non-comment line is `KEY=value`. We collect them into an array of
# `--dart-define` args rather than exporting to the shell, so values with
# spaces or special chars survive intact. We also pluck GOOGLE_MAPS_API_KEY
# into a plain shell var so it can be written to android/local.properties —
# the Flutter Maps SDK reads it from there at native config time, separately
# from the Dart side that reads dart-defines.
DEFINES=()
GOOGLE_MAPS_API_KEY=""
while IFS='=' read -r key value; do
  # Skip blank lines and comments (after trimming leading whitespace).
  key="${key#"${key%%[![:space:]]*}"}"
  [[ -z "$key" || "$key" == \#* ]] && continue
  # Trim surrounding quotes from the value if present.
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  DEFINES+=("--dart-define=${key}=${value}")
  if [[ "$key" == "GOOGLE_MAPS_API_KEY" ]]; then
    GOOGLE_MAPS_API_KEY="$value"
  fi
done < "$ENV_FILE"

if [[ ${#DEFINES[@]} -eq 0 ]]; then
  echo "warning: no keys found in $ENV_FILE — the build will run but maps/places will be broken" >&2
fi

APP_DIR="$REPO_ROOT/apps/$APP"

# Native Maps SDK reads MAPS_API_KEY via the `${MAPS_API_KEY}`
# manifestPlaceholder, which build.gradle.kts now resolves from Gradle's
# `project.findProperty("MAPS_API_KEY")` (i.e. android/gradle.properties).
#
# We deliberately do NOT write to android/local.properties — `flutter run`
# regenerates that file on every debug build from the Flutter template,
# wiping any custom keys. gradle.properties is gitignored and stable.
if [[ -n "$GOOGLE_MAPS_API_KEY" ]]; then
  GRADLE_PROPS="$APP_DIR/android/gradle.properties"
  if [[ -f "$GRADLE_PROPS" ]]; then
    sed -i.bak '/^MAPS_API_KEY=/d' "$GRADLE_PROPS"
    rm -f "$GRADLE_PROPS.bak"
    # If the file doesn't end with a newline, our append would smash onto
    # the previous line (collision with whatever the last property was).
    # tail -c 1 returns empty when the last byte IS a newline.
    if [[ -n "$(tail -c 1 "$GRADLE_PROPS")" ]]; then
      printf '\n' >> "$GRADLE_PROPS"
    fi
  fi
  echo "MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> "$GRADLE_PROPS"
  echo "→ wrote MAPS_API_KEY to $GRADLE_PROPS"

  # iOS native Maps SDK reads `GMSApiKey` from Info.plist, populated at build
  # time from the `$(GOOGLE_MAPS_API_KEY)` xcconfig variable. We write a small
  # Secrets.xcconfig — gitignored, rewritten on every run — and Debug.xcconfig
  # / Release.xcconfig `#include?` it (already in the project). Without this,
  # AppDelegate.swift's GMSServices.provideAPIKey() never fires and the SDK
  # throws GMSServicesException on first map render.
  SECRETS_XCCONFIG="$APP_DIR/ios/Flutter/Secrets.xcconfig"
  cat > "$SECRETS_XCCONFIG" <<EOF
// Auto-generated by tool/run.sh from .env.dev — do NOT commit.
// Re-run tool/run.sh after rotating dev keys.
GOOGLE_MAPS_API_KEY = $GOOGLE_MAPS_API_KEY
EOF
  echo "→ wrote $SECRETS_XCCONFIG"
fi

cd "$APP_DIR"
echo "→ flutter run for apps/$APP with ${#DEFINES[@]} dart-defines"
exec flutter run "${DEFINES[@]}" "$@"
