#!/usr/bin/env bash
# Generates `apps/<app>/ios/Flutter/Secrets.xcconfig` from the environment
# matching the Xcode configuration: `.env.prod` for Release, `.env.dev` for
# Debug/Profile.
#
# Called by an Xcode "Run Script" build phase before the Compile Sources
# phase so the GoogleMaps SDK key (and any other key read by Info.plist
# via $(GOOGLE_MAPS_API_KEY)) is fresh on every Xcode build, without
# requiring the developer to run `tool/run.sh` from the terminal first.
#
# Standalone usage (from repo root):
#   tool/sync-ios-secrets.sh client
#   tool/sync-ios-secrets.sh provider
#   tool/sync-ios-secrets.sh provider prod
#
# Inside an Xcode build phase, Xcode sets `SRCROOT` to `apps/<app>/ios`,
# so the script infers the repo root and app from there if no arg is
# given. .env.dev is shared by both apps and lives at the repo root.

set -euo pipefail

# ── Locate repo root + app ───────────────────────────────────────────────────
if [[ "${1:-}" == "client" || "${1:-}" == "provider" ]]; then
  APP="$1"
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
  APP_IOS_DIR="$REPO_ROOT/apps/$APP/ios"
else
  # Invoked by Xcode — SRCROOT is `apps/<app>/ios`.
  if [[ -z "${SRCROOT:-}" ]]; then
    echo "error: pass <client|provider> when running outside Xcode" >&2
    exit 2
  fi
  APP_IOS_DIR="$SRCROOT"
  APP="$(basename "$(dirname "$SRCROOT")")"
  REPO_ROOT="$(cd "$SRCROOT/../../.." && pwd)"
fi

ENV_KIND="${2:-}"
if [[ -z "$ENV_KIND" ]]; then
  case "${CONFIGURATION:-Debug}" in
    Release*) ENV_KIND="prod" ;;
    *)        ENV_KIND="dev" ;;
  esac
fi
case "$ENV_KIND" in
  dev|prod) ;;
  *)
    echo "error: environment must be 'dev' or 'prod', got '$ENV_KIND'" >&2
    exit 2
    ;;
esac

ENV_FILE="$REPO_ROOT/.env.$ENV_KIND"
SECRETS="$APP_IOS_DIR/Flutter/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  # No env file = nothing to sync. Don't fail the build — the developer
  # may not need maps for whatever target they're building right now.
  # Just leave any existing Secrets.xcconfig untouched.
  echo "warning: $ENV_FILE not found, skipping Secrets.xcconfig sync"
  exit 0
fi

# ── Extract the app/platform key ─────────────────────────────────────────────
GOOGLE_MAPS_API_KEY=""
GOOGLE_MAPS_API_KEY_CLIENT_IOS=""
GOOGLE_MAPS_API_KEY_PROVIDER_IOS=""
while IFS='=' read -r key value; do
  key="${key#"${key%%[![:space:]]*}"}"
  [[ -z "$key" || "$key" == \#* ]] && continue
  value="${value%\"}"; value="${value#\"}"
  value="${value%\'}"; value="${value#\'}"
  case "$key" in
    GOOGLE_MAPS_API_KEY|GOOGLE_MAPS_API_KEY_CLIENT_IOS|GOOGLE_MAPS_API_KEY_PROVIDER_IOS)
      printf -v "$key" '%s' "$value"
      ;;
  esac
done < "$ENV_FILE"

case "$APP" in
  client)   SPECIFIC_KEY="$GOOGLE_MAPS_API_KEY_CLIENT_IOS" ;;
  provider) SPECIFIC_KEY="$GOOGLE_MAPS_API_KEY_PROVIDER_IOS" ;;
esac
SELECTED_KEY="${SPECIFIC_KEY:-$GOOGLE_MAPS_API_KEY}"

case "$SELECTED_KEY" in
  ""|*"..."*|*"replace-me"*|*"REPLACE"*|*"YOUR_"*)
    if [[ "$ENV_KIND" == "prod" ]]; then
      echo "error: iOS Maps key for $APP is missing/placeholder in $ENV_FILE" >&2
      exit 1
    fi
    echo "warning: iOS Maps key for $APP missing from $ENV_FILE"
    exit 0
    ;;
esac

if [[ -z "$SELECTED_KEY" ]]; then
  echo "warning: iOS Maps key for $APP missing from $ENV_FILE"
  exit 0
fi

# ── Write Secrets.xcconfig ───────────────────────────────────────────────────
mkdir -p "$(dirname "$SECRETS")"
cat > "$SECRETS" <<EOF
// Auto-generated by tool/sync-ios-secrets.sh from .env.$ENV_KIND — do NOT commit.
// Regenerated on every Xcode build (Run Script phase in Runner target).
GOOGLE_MAPS_API_KEY = $SELECTED_KEY
EOF
echo "→ wrote $SECRETS (app=$APP env=$ENV_KIND)"
