#!/usr/bin/env bash
# Generates `apps/<app>/ios/Flutter/Secrets.xcconfig` from `.env.dev`.
#
# Called by an Xcode "Run Script" build phase before the Compile Sources
# phase so the GoogleMaps SDK key (and any other key read by Info.plist
# via $(GOOGLE_MAPS_API_KEY)) is fresh on every Xcode build, without
# requiring the developer to run `tool/run.sh` from the terminal first.
#
# Standalone usage (from repo root):
#   tool/sync-ios-secrets.sh client
#   tool/sync-ios-secrets.sh provider
#
# Inside an Xcode build phase, Xcode sets `SRCROOT` to `apps/<app>/ios`,
# so the script infers the repo root and app from there if no arg is
# given. .env.dev is shared by both apps and lives at the repo root.

set -euo pipefail

# ── Locate repo root + app ───────────────────────────────────────────────────
if [[ "${1:-}" == "client" || "${1:-}" == "provider" ]]; then
  APP="$1"
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
  APP_IOS_DIR="$REPO_ROOT/apps/$APP/ios"
else
  # Invoked by Xcode — SRCROOT is `apps/<app>/ios`.
  if [[ -z "${SRCROOT:-}" ]]; then
    echo "error: pass <client|provider> when running outside Xcode" >&2
    exit 2
  fi
  APP_IOS_DIR="$SRCROOT"
  APP="$(basename "$(dirname "$SRCROOT")")"
  REPO_ROOT="$(cd "$SRCROOT/../../.." && pwd)"
fi

ENV_FILE="$REPO_ROOT/.env.dev"
SECRETS="$APP_IOS_DIR/Flutter/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  # No env file = nothing to sync. Don't fail the build — the developer
  # may not need maps for whatever target they're building right now.
  # Just leave any existing Secrets.xcconfig untouched.
  echo "warning: $ENV_FILE not found, skipping Secrets.xcconfig sync"
  exit 0
fi

# ── Extract GOOGLE_MAPS_API_KEY ──────────────────────────────────────────────
GOOGLE_MAPS_API_KEY=""
while IFS='=' read -r key value; do
  key="${key#"${key%%[![:space:]]*}"}"
  [[ -z "$key" || "$key" == \#* ]] && continue
  value="${value%\"}"; value="${value#\"}"
  value="${value%\'}"; value="${value#\'}"
  if [[ "$key" == "GOOGLE_MAPS_API_KEY" ]]; then
    GOOGLE_MAPS_API_KEY="$value"
    break
  fi
done < "$ENV_FILE"

if [[ -z "$GOOGLE_MAPS_API_KEY" ]]; then
  echo "warning: GOOGLE_MAPS_API_KEY missing from $ENV_FILE"
  exit 0
fi

# ── Write Secrets.xcconfig ───────────────────────────────────────────────────
mkdir -p "$(dirname "$SECRETS")"
cat > "$SECRETS" <<EOF
// Auto-generated by tool/sync-ios-secrets.sh from .env.dev — do NOT commit.
// Regenerated on every Xcode build (Run Script phase in Runner target).
GOOGLE_MAPS_API_KEY = $GOOGLE_MAPS_API_KEY
EOF
echo "→ wrote $SECRETS (app=$APP)"
