import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';
import 'package:myshop_client/firebase_options.dart';

import 'src/app/client_app.dart';
import 'src/core/constants/mapbox_config.dart';
import 'src/core/deep_links/referral_deep_link.dart';
import 'src/core/di/providers.dart';
import 'src/core/providers/active_ride_recovery_bridge.dart';
import 'src/core/providers/current_location_provider.dart';
import 'src/core/providers/logout_cleanup_bridge.dart';
import 'src/core/providers/socket_provider.dart';
import 'src/core/services/fcm_service.dart';
import 'src/core/services/local_notification_service.dart';
import 'src/features/auth/providers/auth_controller.dart';

// Note: `firebase_options.dart` is generated by the FlutterFire CLI. If it
// is missing, run from `apps/client`:
//
//   flutterfire configure -p myshop-8b12c \
//       -i com.gilmoretech.myshopclient \
//       -a com.gilmoretech.myshopclient
//
// That writes `lib/firebase_options.dart`, `android/app/google-services.json`
// and `ios/Runner/GoogleService-Info.plist`. After running it, switch the
// `Firebase.initializeApp()` call below to use `options:` and uncomment the
// google-services plugin in the android gradle files.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint('[main] CLIENT app starting — FCM build marker v3');

  MapboxOptions.setAccessToken(MapboxConfig.accessToken);

  final container = ProviderContainer(
    overrides: [
      // Wire real backend services
      authServiceProvider.overrideWith(
        (ref) => ref.watch(realAuthServiceProvider),
      ),
      tokenStorageProvider.overrideWith(
        (ref) => ref.watch(appTokenStorageProvider),
      ),
    ],
  );

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const ClientApp(),
    ),
  );

  // Nothing involving a platform channel or permission dialog is allowed to
  // delay runApp. Start the rest only after Flutter has painted its first
  // frame, so a slow plugin leaves a usable splash/router rather than the
  // operating system's launch screen.
  WidgetsBinding.instance.addPostFrameCallback((_) {
    unawaited(_finishStartup(container));
  });
}

Future<void> _finishStartup(ProviderContainer container) async {
  unawaited(_loadOnboardingPreferences(container));

  // These are synchronous Riverpod subscriptions. Isolate failures so one
  // optional bridge can never prevent the rest of startup.
  for (final activate in <void Function()>[
    () => container.read(socketConnectionProvider),
    () => container.read(clientActiveRideRecoveryBridgeProvider),
    () => container.read(logoutCleanupBridgeProvider),
    () => container.read(referralDeepLinkBridgeProvider),
  ]) {
    try {
      activate();
    } catch (e) {
      debugPrint('[main] startup bridge failed: $e');
    }
  }

  final firebaseReadyFuture = _initializeFirebase();
  final notificationsReadyFuture = _initializeLocalNotifications();
  final firebaseReady = await firebaseReadyFuture;
  await notificationsReadyFuture;

  if (firebaseReady) {
    try {
      // Keep the auth bridge subscribed for the container lifetime and wire
      // notification taps only after FirebaseMessaging is available.
      container.listen<void>(fcmAuthBridgeProvider, (_, __) {});
      container.read(fcmTapBridgeProvider);
      unawaited(container.read(fcmServiceProvider).init().catchError(
            (Object e) => debugPrint('[main] FCM init failed: $e'),
          ));
    } catch (e) {
      debugPrint('[main] FCM bridge setup failed: $e');
    }
  }

  // Warm up GPS without delaying navigation.
  unawaited(container.read(currentLocationServiceProvider).ensure().catchError(
    (Object e) {
      debugPrint('[main] current-location warm-up failed: $e');
      return null;
    },
  ));
}

Future<void> _loadOnboardingPreferences(ProviderContainer container) async {
  try {
    await loadOnboardingFlag(container).timeout(const Duration(seconds: 3));
  } catch (e) {
    debugPrint('[main] onboarding preferences unavailable: $e');
  } finally {
    container.read(onboardingFlagLoadedProvider.notifier).state = true;
  }
}

Future<bool> _initializeFirebase() async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    ).timeout(const Duration(seconds: 8));
    FirebaseMessaging.onBackgroundMessage(fcmBackgroundHandler);
    return true;
  } catch (e) {
    debugPrint('[main] Firebase init failed — push disabled: $e');
    return false;
  }
}

Future<void> _initializeLocalNotifications() async {
  try {
    await LocalNotificationService.instance
        .init()
        .timeout(const Duration(seconds: 5));
  } catch (e) {
    debugPrint('[main] Local notifications init failed: $e');
  }
}
