import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';
import 'package:myshop_client/firebase_options.dart';

import 'src/app/client_app.dart';
import 'src/core/constants/mapbox_config.dart';
import 'src/core/deep_links/referral_deep_link.dart';
import 'src/core/di/providers.dart';
import 'src/core/providers/active_ride_recovery_bridge.dart';
import 'src/core/providers/current_location_provider.dart';
import 'src/core/providers/logout_cleanup_bridge.dart';
import 'src/core/providers/socket_provider.dart';
import 'src/core/services/fcm_service.dart';
import 'src/core/services/local_notification_service.dart';
import 'src/features/auth/providers/auth_controller.dart';

// Note: `firebase_options.dart` is generated by the FlutterFire CLI. If it
// is missing, run from `apps/client`:
//
//   flutterfire configure -p myshop-8b12c \
//       -i com.gilmoretech.myshopclient \
//       -a com.gilmoretech.myshopclient
//
// That writes `lib/firebase_options.dart`, `android/app/google-services.json`
// and `ios/Runner/GoogleService-Info.plist`. After running it, switch the
// `Firebase.initializeApp()` call below to use `options:` and uncomment the
// google-services plugin in the android gradle files.

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint('[main] CLIENT app starting — FCM build marker v3');

  MapboxOptions.setAccessToken(MapboxConfig.accessToken);

  // Firebase — guarded so the rest of the app still boots even if the
  // platform config files (google-services.json / GoogleService-Info.plist)
  // haven't been dropped in yet. Once configured, replace with:
  //   await Firebase.initializeApp(
  //     options: DefaultFirebaseOptions.currentPlatform,
  //   );
  try {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
    // Register the background isolate handler synchronously, before
    // runApp. The plugin commits the handle to the native side here; if
    // we wait until FcmService.init() (fire-and-forget post-runApp), the
    // first cold-start push after install can race the registration and
    // be dropped.
    FirebaseMessaging.onBackgroundMessage(fcmBackgroundHandler);
  } catch (e) {
    debugPrint('[main] Firebase init failed — push disabled for this run: $e');
  }

  // Local notifications — cheap, safe to await. Wrapped in case the
  // platform channel isn't available (e.g. simulator quirks).r
  try {
    await LocalNotificationService.instance.init();
  } catch (e) {
    debugPrint('[main] Local notifications init failed: $e');
  }

  final container = ProviderContainer(
    overrides: [
      // Wire real backend services
      authServiceProvider.overrideWith(
        (ref) => ref.watch(realAuthServiceProvider),
      ),
      tokenStorageProvider.overrideWith(
        (ref) => ref.watch(appTokenStorageProvider),
      ),
    ],
  );

  // Eagerly load the onboarding flag so the router can read it synchronously.
  await loadOnboardingFlag(container);

  // Activate the WebSocket connection provider so it reacts to auth state
  // changes. Connects automatically when the user logs in, disconnects on
  // logout. Incoming events push live updates into Riverpod providers.
  container.read(socketConnectionProvider);

  // On every transition into authenticated, check whether the rider has
  // an in-flight ride that needs to be resumed (force-quit / crash mid-
  // trip). Mirrors the driver-side recovery bridge.
  container.read(clientActiveRideRecoveryBridgeProvider);

  // Register the FCM token with the backend on login; tears it down on
  // logout. Fire this BEFORE runApp so the subscription survives the
  // full app lifetime.
  //
  // Use `listen` (not `read`) so the bridge stays subscribed for the
  // life of the container — without an active listener, Riverpod
  // invalidates the provider on auth-state change but never re-runs
  // the body, which would mean the AuthUnknown → AuthAuthenticated
  // transition silently drops syncToken.
  container.listen<void>(fcmAuthBridgeProvider, (_, __) {});

  // Wire push taps into GoRouter navigation. Must happen AFTER the router
  // provider is reachable — reading it here creates it lazily through the
  // provider graph.
  container.read(fcmTapBridgeProvider);

  // Tear down session-scoped Riverpod state (socket, ride/booking flow,
  // payment notifier, badges, activity feed, pending-payment store) on
  // every transition out of AuthAuthenticated, so a second user signing
  // in on the same install starts clean.
  container.read(logoutCleanupBridgeProvider);

  // Start listening for referral deep links (myshop://refer?code=…). Captures
  // the cold-start link and any links delivered while running, parking the
  // code for the sign-up screen to prefill. Read (not listen) — the bridge
  // holds its own stream subscription for the container's lifetime.
  container.read(referralDeepLinkBridgeProvider);

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const ClientApp(),
    ),
  );

  // Kick off FCM init after the first frame so the permission prompt
  // never blocks the UI. Fire-and-forget — handlers auto-register.
  Future<void>(() async {
    try {
      await container.read(fcmServiceProvider).init();
    } catch (e) {
      debugPrint('[main] FCM init failed: $e');
    }
  });

  // Warm up the device GPS fix so map screens and the "current location"
  // greeting open with the user's actual position instead of the pilot-city
  // default. Fire-and-forget — failures (denied permission, services off)
  // just leave the cache empty and callers fall back gracefully.
  Future<void>(() async {
    try {
      await container.read(currentLocationServiceProvider).ensure();
    } catch (e) {
      debugPrint('[main] current-location warm-up failed: $e');
    }
  });
}
